#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
GLSL to C++ Header Converter
将GLSL着色器文件转换为C++头文件，包含着色器代码字符串
"""

import sys
import os
import re

def remove_comments(content):
    """删除GLSL代码中的所有注释，包括单行和多行注释"""
    # 删除多行注释 /* ... */
    content = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)
    # 删除单行注释 // ...
    content = re.sub(r'//.*', '', content)
    return content

def clean_whitespace(content):
    """清理多余的空白字符和空行"""
    # 分割成行
    lines = content.split('\n')
    # 移除每行末尾的空白字符，但保留有内容的行
    cleaned_lines = []
    for line in lines:
        stripped = line.rstrip()
        # 保留非空行和只包含空白字符的行（转换为空行）
        if stripped or (not stripped and line.strip() == ''):
            cleaned_lines.append(stripped)
    
    # 移除连续的空行，只保留单个空行
    result_lines = []
    prev_empty = False
    for line in cleaned_lines:
        if line.strip() == '':
            if not prev_empty:
                result_lines.append('')
            prev_empty = True
        else:
            result_lines.append(line)
            prev_empty = False
    
    # 移除开头和结尾的空行
    while result_lines and result_lines[0] == '':
        result_lines.pop(0)
    while result_lines and result_lines[-1] == '':
        result_lines.pop()
    
    return '\n'.join(result_lines)

def escape_string_for_cpp(content):
    """将字符串中的特殊字符转义，以便在C++代码中使用"""
    # 转义反斜杠
    content = content.replace('\\', '\\\\')
    # 转义双引号
    content = content.replace('"', '\\"')
    # 将换行符转换为\\n字符串
    content = content.replace('\n', '\\n')
    return content

def generate_variable_name(filename):
    """根据文件名生成变量名"""
    base_name = os.path.basename(filename)
    file_name_without_ext = os.path.splitext(base_name)[0]
    
    # 根据文件类型生成变量名
    if "vert" in file_name_without_ext:
        return "WIND_VERTEX_SHADER"
    elif "frag" in file_name_without_ext:
        return "WIND_FRAGMENT_SHADER"
    else:
        # 通用命名规则
        return file_name_without_ext.upper().replace('.', '_').replace('-', '_') + "_SHADER"

def main():
    # 检查命令行参数
    if len(sys.argv) != 3:
        print("用法: python Convert_GLSL_to_h.py <输入GLSL文件> <输出头文件>")
        print("示例: python Convert_GLSL_to_h.py wind.vert.glsl wind.vert.h")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    # 检查输入文件是否存在
    if not os.path.exists(input_file):
        print(f"错误: 输入文件 '{input_file}' 不存在")
        sys.exit(1)
    
    try:
        # 使用UTF-8编码读取文件内容
        with open(input_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # 删除所有注释
        content = remove_comments(content)
        
        # 清理空白字符
        content = clean_whitespace(content)
        
        # 转义内容
        escaped_content = escape_string_for_cpp(content)
        
        # 生成变量名
        var_name = generate_variable_name(input_file)
        
        # 确保输出目录存在
        output_dir = os.path.dirname(output_file)
        if output_dir and not os.path.exists(output_dir):
            os.makedirs(output_dir)
        
        # 使用UTF-8编码写入输出文件
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("#pragma once\n\n")
            f.write(f"// Auto-generated from {os.path.basename(input_file)}\n")
            f.write(f"// Do not edit this file manually\n\n")
            f.write(f"const char* const {var_name} = \"{escaped_content}\";\n")
        
        print(f"成功转换: {input_file} -> {output_file}")
        print(f"变量名: {var_name}")
        
    except Exception as e:
        print(f"错误: 转换失败 - {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    main()